### ISSUE TITLE
provide liboidc-agent as debian package

### ISSUE THREAD

**Issue by zachmann** [indigo-dc/oidc-agent#101]
I guess it would be the right way to provide the liboidc-agent library as a package.

We might want to provide it at a dynamic link library, not (only) a static one.

**Comment by marcvs** [comment]
Ok; so make sure that it can be installed into a separate folder, specified in a similar way as we do for the installation of oidc-agent itself.

**Comment by zachmann** [comment]
Creation of the shared library is included in the [shared_library](https://github.com/indigo-dc/oidc-agent/tree/shared-library) branch.

So at some point packages can be build for ```liboidc-agent2``` and ```liboidc-agent-dev```.
There are install rules in the Makefile:
- ```install_lib```
- ```install_lib-dev```

I tried to prepare everything as good as possible, but building packages for shared libraries seems not to be trivial.
@marcvs I guess you should check this for more information:
- https://www.debian.org/doc/manuals/maint-guide/advanced.en.html#ftn.idm3864

When we have those 3 packages: ```liboidc-agent-dev``` as well as ```oidc-agent``` both depend on ```liboidc-agent2```
