### ISSUE TITLE
encrypt relevant ipc-communication

### ISSUE THREAD

**Issue by zachmann** [indigo-dc/oidc-agent#113]
We might want to encrypt the communication between oidc-agent and oidc-add / oidc-gen / oidc-token-exchange. 
This communication contains sensitive information (client_id/client_secret + in some cases refresh_token). For oidc-token and other clients that only request an access token, it is not necessary. The most secret information there is the access token, that can be requested by any application. So we should not require encryption for clients (additional complexity), but we should accept it. For liboidc-agent it's no problem to offer a secure function that includes encryption.

We can use libsodium for key exchange, however this requires libsodium 1.0.12 (currently using 1.0.11). 
- We currently build libsodium for xenial -> no problem to build 12 instead.
- Bionic has version >= 12
- stretch only has 11 -> but backports has version >= 12
- buster has version >= 12

**Comment by marcvs** [comment]
You could make it  a compiletime option. I.e. a configuration script at compiletime will set that option  (e.g. in the Makefile). In the code you can then use `#ifdef` and `#endif` to conditionally use it or not.

**Comment by zachmann** [comment]
First, we then would have to check dependency version depending on that option (with encryption we need libsodium 1.0.12 without just .11).
Second, I don't really see the reason for a compile time option if it is only to enable or disable encryption.
I see the following two options:
- enable it on default (and maybe allow to disable it via cli and/or env var) and require libsodium 1.0.12
- don't depend on 1.0.12 and only enable it when the installed version is high enough -> requires compile time option
The problem with the second option is, that we don't know which version might be installed on the user's system, so we basically would have to provide two different packages. That's not nice.

So, I would go for 'enable on default and require libsodium 1.0.12'.
Only dependency problem will be with stretch, but we already build libsodium for xenial, so we also can provide it for stretch. It's also in backports (with .16) so if one uses these he does not have to use our's.

**Comment by zachmann** [comment]
But if we decide to depend on .12 we can bump this number up to .14 
For the distributions that doesn't really make a difference, and then we can use base64 encoding isntead of hex encoding (see #106)

**Comment by marcvs** [comment]
It should actually work; We can basically ship the updated libsodium18_1.0.14-1 also with stretch.
I'll go test locally with increased requirements.

**Comment by marcvs** [comment]
It should actually work; We can basically ship the updated libsodium18_1.0.14-1 also with stretch.
I'll go test locally with increased requirements.

**Comment by marcvs** [comment]
libsodium_1.0.13 only builds on stretch but not on xenial. Xenial is a required target platform, though

I didn't find a libsodium_1.0.12 versions.

**Comment by zachmann** [comment]
ok, waht about 1.0.14?
What do you need for build it? Are the [release sources](https://github.com/jedisct1/libsodium/releases) enough?

**Comment by zachmann** [comment]
So there's no (reasonable) way to get an newer libsodium version on xenial. At least not as a shared library.
However, I think we can also link the static library directly into oidc-agent. While the static library itself won't be available for xenial (provided in libsodium-dev) we should be able to use it there.

Of course this will increase the binary size of the oidc-agent executables, but we also get rid of the user dependency for libsodium.

**Comment by marcvs** [comment]
Ok; so we build different packages for xenial and for the rest of te world.

I'm not exactly sure how to organise this. I suggest we create a xenial branch, in which the encryption for IPC is not used, an hence the debian/control file (and changelog) are different.

Probably that package should also be named differently, right?

**Comment by zachmann** [comment]
No, we still can include libsodium on xenial.
We will get rid of the user dependecy, because we will link statically.
For building we still require libsodium-dev (>=1.0.14), that's theoretically not available for xenial, but we can provide the needed files to the build process anyway.

Only difference for xenial and other distributions: On other distributions we can depend (and will) on libsodium-dev, for xenial we have to use another debian control file, without this dependency and provide use the static library from e.g. bionic
