### ISSUE TITLE
oidc-agent persistency

### ISSUE THREAD

**Issue by zachmann** [indigo-dc/oidc-agent#116]
Input from @vykozlov 
[Persistence of oidc-agent as described in [GitBook](https://indigo-dc.gitbooks.io/oidc-agent/oidc-agent.html) ...]

I still have to start oidc-agent manually first time. Well, I can modify it to following lines in .bashrc:
```
# Start oidc-agent if not already running
if [ -f /tmp/oidc-agent-$USER.env ]; then
    . /tmp/oidc-agent-$USER.env
else
   eval $(oidc-agent > /tmp/oidc-agent-$USER.env)
fi
```
i.e. if that file "oidc-agent-$USER.env" exists, export settings from it, if it does not, run the agent.

Still a problem, agent might be killed but the file will exist. However, this is what you can do in oidc-agent itself:

1. Start agent, write pre-defined file with e.g. OIDC_SOCK and PID
2. At every start, check if
   a) this pre-defined file exists
   b) belongs to the user
   c) PID from the file is indeed in the memory
   e) OIDC_SOCK exists
   f) if all above is true, do _not_ start new instance but return 'old' OIDC_SOCK value and OIDCD_PID, almost as you do it now
   g) if PID is not found in the memory or something else, start new instance, return new OIDC_SOCK and OIDC_PID

I mean, now you do not change environment either but when I do:
```$ eval $(oidc-agent)```

This sets environment. But always new instance is started and new OIDCD_PID and OIDC_SOCK are returned. If you do checks in oidc-agent, you may skip starting new instance and return actual OIDCD_PID and OIDC_SOCK values. Additional key may force starting new instance.

**Comment by zachmann** [comment]
We can add something like that. But I'm not sure about defaults. What should be default behavior, what might be controlled with options?

I see three possible use cases:
- simply starting a new agent, nevertheless what's already running
- start a new agent only if not presented in the current environment
- the above described file stuff

However, one problem to keep in mind if we do the above described checks:
If the agent is killed and restarted, we can update the tmp file with the new information, but it will not be available in any other terminal. The file has to be sourced again so that the environment can change.
So if the agent is killed, that's bad.

@marcvs like to hear your opinion on all of this topic

**Comment by marcvs** [comment]
I think we should follow the ssh-agent model in that respect. I.e. it is not part of the agent to check for running instances. 

One fix for the above script:
```
# Start oidc-agent if not already running
if [ -f /tmp/oidc-agent-$USER.env ]; then
    . /tmp/oidc-agent-$USER.env
else
    oidc-agent > /tmp/oidc-agent-$USER.env
    . /tmp/oidc-agent-$USER.env
fi
```
