### ISSUE TITLE
Missing integration with X

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#169]
This is what I did for my Debian machines.

I created the file `/etc/X11/Xsession.d/91oidc-agent` with the following content:
```
if has_option use-oidc-agent; then
    eval `/usr/bin/oidc-agent`
fi 
```

I then added `use-oidc-agent` to `/etc/X11/Xsession.options`.  Here's the current contents of that file:
```
# $Id: Xsession.options 189 2005-06-11 00:04:27Z branden $
#
# configuration options for /etc/X11/Xsession
# See Xsession.options(5) for an explanation of the available options.
allow-failsafe
allow-user-resources
allow-user-xsession
use-ssh-agent
use-session-dbus
use-oidc-agent
```

This way, `oidc-agent` is available throughout my entire X session (and all terminals therein) much the same way as `ssh-agent`.

I think it would be good if the `/etc/X11/Xsession.d/91oidc-agent` file was available as part of the package, perhaps also automatically adding the `use-oidc-agent` option in `Xsession.options`

**Comment by zachmann** [comment]
Thanks, for pointing that out. 
It was actually quite easy to integrate.
oidc-agent 2.3.0 will have support for integration with X; which is also enabled by default (though Xsession.options).
