### ISSUE TITLE
Add necessary info for manual registration

### ISSUE THREAD

**Issue by marcvs** [indigo-dc/oidc-agent#183]
When trying to register a client at unity, I'm told that dynamic registration does not work.
I'm given a URL where I register my client.

In unity I have to provide a redirect url, that I don't know. Putting one extra line of output with the list of redirect URIs would be helpful

**Comment by zachmann** [comment]
The redirect url can be chosen by the user. It is not dictated by oidc-agent. However, it has to be of a specific form. 

For parameters for manual client registration users should refer to to dcoumentation. Especially the part about different [providers](https://indigo-dc.gitbooks.io/oidc-agent/provider.html) and the part for the [Client configuration values](https://indigo-dc.gitbooks.io/oidc-agent/oidc-gen.html#client-configuration-values).

However, hdf is currently missing in the "How to register a client for..." provider documentation.
I will add it.
