### ISSUE TITLE
more noneinteractive pw options

### ISSUE THREAD

**Issue by zachmann** [indigo-dc/oidc-agent#194]
when using oidc-gen and oidc-add the default way to obtain the encryption/decryption password is to prompt the user on the command line.
With verison 2.3.0 there's already the ```--pw-cmd``` option added. It would be nice to also have an ```--pw``` or ```--password``` option to specify the password on the command line / script and a ```pw-prompt``` or ```--pw-gui-prompt``` option that pormpts the user, but not on the command line, but by using the gui prompt (ssh-askpass).

Somewhat related to #96

**Comment by paulmillar** [comment]
At the risk of pointing out the obvious: a `--password` argument would be rather insecure.  On most unix-like systems, any use can get a list of all processes, including the command-line.

Perhaps for inspiration, please review the pass phrase options for openssl, as documented in the openssl(1) man page.

**Comment by marcvs** [comment]
I remember that pipes (i.e. stdin) are regarded safe for this usecase

**Comment by zachmann** [comment]
In version 4.0.0 the `--pw-file` option will be added. This will read the first line of the passed file as password.
There will also be improvements regarding the prompting of user, i.e. the user can define if prompting for the password (if required) is done through cli or gui.

Other options for passwords are not planned.
