### ISSUE TITLE
make agent socket dir accessable for group

### ISSUE THREAD

**Issue by zachmann** [indigo-dc/oidc-agent#210]
Currently the agent socket directory and the socket are only accessable by the user that runs oidc-agent.
This is a security feature.

However, there might be situations, where process running as another user also want to obtain an AT from the agent and cannot run under another user.
One solutation in such a case would be adding user that runs the agent and other users to a common group (e.g. 'oidc-agent') and changing the group ownership of the socket and directory to this group. This way other users can communicate with the agent.

This is possible without support from oidc-agent. However, it can be eased by supporting this by changing the group ownership automatically when creating the socket dir.

This feature is completely optional and only applied when the argument is provided onagent startup.

**Comment by zachmann** [comment]
Still have to test it on MacOS, and add documentation

**Comment by marcvs** [comment]
Would it not be possible for the other user to start his own agent?

**Comment by zachmann** [comment]
sure, but it needs (his own) account configs in his own home directory and have to be loaded into both / multiple agents. 
I think it is more convenient to have only one agent per human and if this human has multiple users he can grant access to the agent to the whole group

**Comment by marcvs** [comment]
Ah, sure. Makes perfect sense in that case.
