### ISSUE TITLE
Need an easy way to find out what accounts are loaded

### ISSUE THREAD

**Issue by DrDaveD** [indigo-dc/oidc-agent#231]
I'm writing oidc-keychain, and one of the things it needs to do is to load the given account shortnames when they aren't already loaded into oidc-agent.  The problem is I don't see a way to find out which accounts are loaded.  ssh does the analogous with ssh-add -l, but oidc-add -l lists which accounts are available, not which ones are loaded.  I can find out by attempting to issue a token with oidc-token and throwing away any given token, but that seems a bit extreme.  I also don't think it's probably a good idea to change existing behavior.  What do the developers recommend for a new option to do this?

**Comment by zachmann** [comment]
Sorry, for the delayed response.
This feature was already implemented, but was removed since there wasn't a usecase for it and we thought it would be more secure without this option.
But with a usecase there's no reason to not bring this back.

**Comment by zachmann** [comment]
The `-a` and `--loaded` option are added with the next release version to oidc-add
