### ISSUE TITLE
Bash completion missing for oidc-keychain

### ISSUE THREAD

**Issue by DrDaveD** [indigo-dc/oidc-agent#241]
Bash completion is missing for oidc-keychain in the dev_3.3.0 branch.

**Comment by zachmann** [comment]
Yes I had this in mind, but then forgot about it.
Good point. I'll add it.

**Comment by zachmann** [comment]
I implemented the following:
Bash completion suggests all `oidc-agent` options and additionally `--acounts`. After `--acounts` was used only account shortnames are suggested.
