### ISSUE TITLE
Using a variable for the rpm .spec file interferes with the OSG build process

### ISSUE THREAD

**Issue by DrDaveD** [indigo-dc/oidc-agent#249]
In #230 the rpm spec file was modified for the OSG build process, but it didn't go far enough.  We can't pass a value for _version on the rpm build line; we need the version number to be hardcoded.  What do you think about having an oidc-agent.spec.in, generating oidc-agent.spec with the version number, and checking that back into git whenever there's a new release?  I have seen other projects that do that, putting something like `@VERSION@` in the spec.in file and generating the spec in a shell script with sed.

**Comment by zachmann** [comment]
We can accept the proposed changes. Are you willing to submit a pull request?

**Comment by DrDaveD** [comment]
I could. Is your script for building rpms and/or making a new release included in the source repository somewhere?  I don't see it offhand.

**Comment by zachmann** [comment]
There is no special build script, only the rpm target in the makefile
