### ISSUE TITLE
oidc-gen leaves world-readable /tmp file, and with a name that could clash

### ISSUE THREAD

**Issue by DrDaveD** [indigo-dc/oidc-agent#250]
oidc-gen leaves a world-readable file `/tmp/oidc-gen:<accountname>` that looks to me like it contains some pretty sensitive unencrypted information.  The name could also easily clash if there are multiple users on the same machine that choose the same account name.

**Comment by zachmann** [comment]
Some remarks:
- it was not intended to be world readable
- usually the file should not be left over. After a successful oidc-gen run it will be deleted and only exists for limited amount of time. However, there might be situations where the file still lays around, that's the reason why it is in `/tmp` so it is eventually cleaned up.
- It is only created when dynamic client registration is used
- It contains the client config the the dynamically registered client, no user information.

Unfortunately I don't see a way to have this information encrypted without reducing user experience significantly.

However, we can improve on some aspects, and get rid of this file entirely  by moving this information to the agent.

**Comment by zachmann** [comment]
With the next release, this information is no longer written to a temporary file, but stored within the agent.
