### ISSUE TITLE
apt-key adv does not work

### ISSUE THREAD

**Issue by belfhi** [indigo-dc/oidc-agent#255]
Hello,
the command to add the key in the gitbook does not work.
Using curl to add the key does, though.
`curl repo.data.kit.edu/key.pgp | apt-key add -`

**Comment by marcvs** [comment]
Do you have an error message for me?

**Comment by belfhi** [comment]
The command just hung for a couple of minutes until I killed it, withough output.
It works now, though, so maybe it was an unreachble server?

**Comment by marcvs** [comment]
Ooops. I'll check with the networking people.
Thanks anyways!
