### ISSUE TITLE
oidc-agent documentation not reachable anymore

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-dc/oidc-agent#256]
I get an error if I try to access oidc-agent documentation:
https://indigo-dc.gitbooks.io/oidc-agent/
This is probably due to gitbook shutdown of legacy projects?
I also guess this affects all the indigo stuff that used gitbooks hosted documentation.

In any case, the docs is no longer available.

**Comment by zachmann** [comment]
For me it is still reachable.
Maybe it was only a temporary problem?

**Comment by andreaceccanti** [comment]
Yes, I guess it was. Now I can also reach the docs. I was worried since a few days ago they warned about shutting down some online services...
