### ISSUE TITLE
Allow user to rename an account's shortname

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#258]
The `oidc-gen` command allows a user to create an account with a specific short name.  That short name is then used when loading the identity with the `oidc-add` command and then in the `oidc-token` command to obtain an access token.

There is currently no way to change the short name, other than deleting the account and running `oidc-gen` to re-authenticated.

Sometimes I would like to rename the account's shortname, as the original choice turned out to be sub-optimal.  This is currently not possible; for example, simply renaming the file (with the account's shortname) located in `~/.config/oidc-agent/` directory results in inconsistent behaviour.  Loading the identity with `oidc-add` works with the new name, but `oidc-token` only yields a token when run with the old shortname.

**Comment by zachmann** [comment]
You're right this should be improved.

Current workaround:
1. Decrypt the file content to a new config file: `oidc-gen -p <shortname> > ~/.config/oidc-agent/<new_shortname>`
2. Edit the `name` in the new file
3. Encrypt the new file: `oidc-gen -u <new_shortname>`
4. Delete the old config file: `rm ~/.config/oidc-agent/<short_name>`
