### ISSUE TITLE
Include hostname in registered client name

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#262]
Currently, oidc-gen/oidc-agent registers itself with the OP using a name like `oidc-agent:<ID>` where `<ID>` is the short name for the account.

If a user registers the same OP on multiple machines, they are likely to choose the same short-name for that OP.  For example, I use the same account short name (`XDC`) for the oidc-agent accounts (on different machines) that correspond to my identity on the https://iam.extreme-datacloud.eu/ OP.

This results in the oidc-agent registrations from different machines having the same name within the OP.  Therefore, it is not easy to identify which registration corresponds to a specific oidc-agent instance.

One relatively easy way to improve this is to include the machine's name in the account name; e.g., `oidc-agent:<hostname>:<ID>`.  I imagine the shortname (not the FQDN) should be sufficient under most circumstances, but including the FQDN should also be fine.

**Comment by zachmann** [comment]
See also #54. As noted there, the configuration files can be copied between machines, in this case including the machine's name might be confusing. I would like to keep the ability to easily copy account configuration files between machines.
However, there is a way to include an additional user given identifier, using the `--cnid` option.

**Comment by paulmillar** [comment]
(I'm glad you found #54. I was sure this topic has come up in the past, but I didn't find the earlier issue!)

The `--cnid` option certainly helps -- sorry, I missed that this option was added.

We could perhaps still argue about what default value makes the most sense; I still think taking the `uname -n` output as the default value for cnid (but allowing a user to override this) would be less confusing overall.

For comparison, by default an ssh public key _does_ include the hostname, albeit in the comment section:

```
$ cat ~/.ssh/id_rsa.pub
ssh-rsa AAA[...]== paul@sprocket
```

However, I guess I can try to remember to specify the `--cnid` when registering clients.
