### ISSUE TITLE
Background running of oidc-agent

### ISSUE THREAD

**Issue by willfurnell** [indigo-dc/oidc-agent#270]
Hello, 

Apologies if this isn't the right place to raise this.

One of our use cases for OIDC tokens would be access to resources during long running jobs - with the jobs running long after the user logs out of the system. What would be the best way to achieve this using oidc-agent please - if it is possible, effectively refreshing tokens whilst the user is logged out of the system?

Thank you!

**Comment by marcvs** [comment]
We have plans to address this issue. We've considered several approaches and security models. Therefore: If you are ok with shipping your refresh token to the infrastructure (thereby accepting the risk that anybody with access to your remote VM (and sufficient criminal energy), might impersonate you until the RT is revoked) then you can use oidc-agent.

If you can wait: I expect early versions of the next product "my-token" to be available from start of 2021. It should become stable throughout that year.

**Comment by willfurnell** [comment]
Thanks very much for the information!

**Comment by zachmann** [comment]
Additional to the mytoken service which is in development, we have now a central oidc-agent-server available. 

The basic concept is:
- The `oidc-agent-server` is running on a server available for multiple clients.
- `oidc-add --remote` can be used to load an locally existing agent account config to the remote server.
- A new shortname is returned
- The new shortname can be used with oidc-token from multiple locations to obtain ATs.

If this is of interesset for you please check https://indigo-dc.gitbook.io/oidc-agent/user/oidc-agent-server for more details and feel free to ask questions.
