### ISSUE TITLE
oidc-token of v4.0.0 does implicitly add configurations

### ISSUE THREAD

**Issue by marcvs** [indigo-dc/oidc-agent#277]
In previous versions running oidc-token <config> would prompt for a password, when a config was not yet loaded. 

oidc-add works well, but uses the console to prompt for the password

ssh-askpass is installed though.

**Comment by zachmann** [comment]
I don't completely get the problem, but note the following:
In v4.0.0 ssh-askpass is not longer used to create gui prompts. Instead `oidc-prompt` is used. This calls `yad`. If you don't get an gui password prompt where you normally got one, check if you have installed the `oidc-agent-prompt` package.

**Comment by marcvs** [comment]
I don't have `yad` installed and I don't find the `oidc-agent-prompt` package.

**Comment by zachmann** [comment]
It isn't yet in any repository. But when you build the debian package with `make deb` it will also build an `oidc-agent-prompt` package. This one will depend on `yad`.
