### ISSUE TITLE
Last link in readme points to invalid url

### ISSUE THREAD

**Issue by marcvs** [indigo-dc/oidc-agent#281]
The link points to:
https://indigo-dc.gitbook.io/oidc-agent/install#from-source
but should probably point to 
https://indigo-dc.gitbook.io/oidc-agent/installation (which is not directly "from source" though)

**Comment by BorjaEst** [comment]
Direct should be this one:
https://indigo-dc.gitbook.io/oidc-agent/installation/install#from-source
