### ISSUE TITLE
How to save refresh token to a file and load it elsewhere?

### ISSUE THREAD

**Issue by matyasselmeci** [indigo-dc/oidc-agent#285]
I'm putting together a webapp (using FLAAT) and want to test it using bearer tokens.
I have a small container with oidc-agent installed; to get a refresh token, I start up the container and use the device workflow (`oidc-gen -w device "mytoken"`).
Is there a way I can save the refresh token to a file so that if I have a fresh container, I can load it back and generate bearer tokens?
(Alternately, can I just get a really long-lived bearer token?)

**Comment by marcvs** [comment]
Sure; The account configuration is saved in $HOME/.config/oidc-agent/<shortname>
You can copy that to different hosts, and use it via oidc-add.

**Comment by zachmann** [comment]
Note that if `~/.config` doesn't exist dir oidc-agent directory is located at `~/.oidc-agent` which is more likely to be case in the container environment. In their should be a file that in your case is called `mytoken`. As Marcus said you can copy that file and then use it with `oidc-add`and `oidc-token`.

**Comment by matyasselmeci** [comment]
Thanks, that works!
