### ISSUE TITLE
Providing oidc-agent package for Ubuntu 20.04

### ISSUE THREAD

**Issue by tdviet** [indigo-dc/oidc-agent#302]
Ubuntu 20.04 is mainstream now, but there is no oidc-agent package for the distribution. Installing oidc-agent package made for 18.04 on 20.04 finished with error.

**Comment by marcvs** [comment]
We're also building packages for Ubuntu 20.04. See http://repo.data.kit.edu  (I fixed the missing 20.04)

**Comment by zachmann** [comment]
@marcvs you're right - in theory - in practice, there aren't any packages there yet.

**Comment by zachmann** [comment]
I build the last release for ubuntu 20.04 and copied it to the server.
You should now be able to install it from repo.data.kit.edu
