### ISSUE TITLE
Suggestions for improvement: to reduce dependencies on Xsession

### ISSUE THREAD

**Issue by tdviet** [indigo-dc/oidc-agent#303]
First, thank you for creating packages for 20.04. I installed oidc-agent successfully on a VM. However, it requires also nearly hundred of other packages for Xwindows, it is too much if users do not have  Xwindows and need only command-line client and agent.

Is it possible to make the Xsession dependency optional, e.g. make a meta-package for X dependence, and another without X?

**Comment by zachmann** [comment]
@marcvs can comment on the details. He already did some work on this. So this will be addressed with the next release.

**Comment by marcvs** [comment]
You can use the development repository for ubuntu:
`deb http://repo.data.kit.edu/ubuntu/devel ./`
