### ISSUE TITLE
mapfile command not found on OS X

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-dc/oidc-agent#315]
Dear OIDC agent devs, 
I get the following error on OS X trying to use oidc-keychain (instead of agent):

```
❯ eval $(oidc-keychain --no-autoload)
/usr/local/bin/oidc-keychain: line 145: mapfile: command not found
oidc-keychain: Agent pid 31402
```

This is OS X Mojave, and oidc-agent is installed via brew

**Comment by zachmann** [comment]
Hi @andreaceccanti 
I replace the call to `mapfile`. Can you verify that the version at https://github.com/indigo-dc/oidc-agent/blob/b27139882b645daaa2ff66de525586246316a8e3/src/oidc-keychain/oidc-keychain works correctly.

**Comment by zachmann** [comment]
Note, that in version 4.1.0 we will introduce `oidc-agent-service` that can be used to easily restart the agent (and also to reuse it). This might be an alternative to `oidc-keychain`.
