### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by marcvs** [indigo-dc/oidc-agent#326]
oidc-gen apparently called `links` in one case. It should rather try to do the device code flow or to run a "real" browser

**Comment by zachmann** [comment]
When doing the authorization code flow, oidc-gen prints the authorization url, but also tries to open it for the user. We generally want to do this in the user's default browser.
The "url-opener" mechanism is defined in [settings.h](https://github.com/indigo-dc/oidc-agent/blob/d69b4fc8122234e3ee3ac1b7caea1e0bef241037/src/defines/settings.h#L72-L76). On linux `xdg-open` is used, on macos `open`.
As far as I know this is the way how to open urls in the default browser from the command line.

`links` does not appear in our source code at all.
