### ISSUE TITLE
oidc-agent-service uses incorrect path for oidc-agent on MacOS

### ISSUE THREAD

**Issue by nulltrope** [indigo-dc/oidc-agent#334]
I just installed on MacOS using brew [following these instructions](https://indigo-dc.gitbook.io/oidc-agent/installation/installation#install-with-homebrew) and when trying to start `oidc-agent-service` I get the following:

```bash
eval `oidc-agent-service use`
/usr/local/bin/oidc-agent-service: line 73: /usr/bin/oidc-agent: No such file or directory
```

I suspect this is because brew installed the binaries at `/usr/local/bin/` instead of `/usr/bin/`:

```bash
ls /usr/local/bin/ | grep oidc
oidc-add
oidc-agent
oidc-agent-service
oidc-gen
oidc-keychain
oidc-prompt
oidc-token
```

For reference, I am using homebrew version 3.2.3 and MacOS Catalina version 10.15.7

**Comment by zachmann** [comment]
Thanks for the information. I don't have a Mac so it is possible that I'm not aware of some things.

I'll fixed it, so now the correct path should be used.
Can you please verify that now everything works as expected?

**Comment by nulltrope** [comment]
Yes I just upgraded and that fixes it, thanks! 

```bash
eval `oidc-agent-service use`
82390
```
