### ISSUE TITLE
oidc-gen --accounts and oidc-add --list include log file

### ISSUE THREAD

**Issue by nulltrope** [indigo-dc/oidc-agent#335]
When running both `oidc-gen --accounts` and `oidc-add --list` to list all client configurations, the `oidc-agent.log` file is also included in the list. 

E.g.
```
oidc-add --list
The following account configurations are usable:
oidc-agent.log
oidc-service-test
```

I am guessing the function just lists any files in the `.config/oidc-agent` dir not matching `issuer.config`, but does not exclude the log file.

I am running oidc-agent version 4.1.1 on Mac OS 10.15.7

**Comment by zachmann** [comment]
> I am guessing the function just lists any files in the `.config/oidc-agent` dir not matching `issuer.config`, but does not exclude the log file.
That's basically correct. Files ending with `.config` or `.clientconfig` are ignored and other files are listed.
This is again related to macos, since the `oidc-agent.log` is only recreated on macos (other systems use syslog).

But of course you're right, the file should not be listed.
