### ISSUE TITLE
allow specifying socket path not under /tmp

### ISSUE THREAD

**Issue by zachmann** [indigo-dc/oidc-agent#345]
As requested by @edquist in #344 

> Greetings!
> 
> We would like to specify an explicit socket path for `oidc-agent` to use. The other `oidc-*` programs use whatever is specified in the `OIDC_SOCK` env var, but `oidc-agent` generates it with a hard-coded `/tmp/oidc-XXXXXX` template for `mkdtemp(3)`.
> 
> How would you feel about providing a way for `oidc-agent` to create its socket file somewhere other than under `/tmp` ?
> 
> Ideas include:
> 
>     * add a command-line option to specify the target oidc socket file path
> 
>     * use `OIDC_SOCK` if specified
> 
>     * use a different `OIDC_*` env var for this purpose
>       (if for instance you are worried about collision with an existing `OIDC_SOCK` from a previous `oidc-agent` run)
> 
>     * respect the `TMPDIR` env var, if set, for providing a base location other than `/tmp`
> 
> 
> The last option seemed like the lowest-hanging fruit, so that's what i've implemented in this PR; but i'd be happy with any solution to the problem that lets us specify another location for the socket file, or at least the base directory for it.
> 
> Thanks for your consideration!

**Comment by zachmann** [comment]
It seems reasonable to implement this. @edquist I'm curious what your use-case is where the socket cannot be located under
`/tmp`, but independent from the use case, it is something we can easily support.

I'll merge #344 into a new feature branch and use it as a starting point. I want to keep the use of `TMPDIR` you implemented there. Additionally, I implement a command-line option to specify the socket path.

**Comment by edquist** [comment]
Thank you @zachmann!

> independent from the use case, it is something we can easily support

> Additionally, I implement a command-line option to specify the socket path.

Sounds great!

Notably, `ssh-agent(1)` also respects `TMPDIR` and has an option for an explicit path:
```
     -a bind_address
             Bind the agent to the UNIX-domain socket bind_address.
             The default is $TMPDIR/ssh-XXXXXXXXXX/agent.<ppid>.
```

So this will give `oidc-agent` the same functionality.

...

> I'm curious what your use-case is where the socket cannot be located under `/tmp`

Right, so we are creating a token renewal service that uses the `oidc-*` tools.

It's not a strict requirement, but, as @bbockelm [comments in our ticket](https://opensciencegrid.atlassian.net/browse/SOFTWARE-4719?focusedCommentId=365127&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-365127), we would like to avoid the service littering under `/tmp`.

Ideally we'd have a fixed socket path for the service (something like `/var/run/osg-token-renewer/oidc-agent.sock`), which a new command line option would allow. But the `TMPDIR` support at least helps avoid exposing the service's socket file(s) in the system-wide `/tmp`.
