### ISSUE TITLE
Problem revoking a refresh token with Helmholtz-AAI

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#351]
I'm trying to delete an account, which involves revoking the refresh token; however, the revocation fails.

The following is an example showing the problem:

```
[paul@paul-oidc-agent ~]$ oidc-gen -d HELMHOLTZ
Enter decryption password for account config 'HELMHOLTZ': 
Do you really want to delete this configuration? [No/yes/quit]: yes
Error: Could not revoke token: invalid_request: Invalid request; To access the token revocation endpoint a client_id must be provided
Do you want to unload and delete anyway. You then have to revoke the refresh token manually. [No/yes/quit]: No
The account was not removed from oidc-agent due to the above listed error. You can fix the error and try it again.
[paul@paul-oidc-agent ~]$ 
```

I note that the Helmholtz AAI doesn't support automatic client registration, but uses a public client instead.

`oidc-gen` knows the Helmholtz AAI public client ID and secret and uses this successfully when obtaining the refresh token.

Perhaps `oidc-gen` isn't using the public client id & secret when attempting to revoke the  refresh token.

**Comment by marcvs** [comment]
I checked with Sander. He found three unsuccessful tries to revoke a Refresh Token. He is not sure if there is a relation.
They failed because the `client_id` was missing. @zachmann : Could you check, pls?

**Comment by zachmann** [comment]
We don;t post the `client_id` in the revocation request body, IMO this is in line with the spec, that does not mention the client id as part of the request. However, it requires that client authentication is included. We include Basic client authentication with revocation requests. So probably unity does not retrieve the client id from the authorization header. However, I have to investigate this more.

**Comment by zachmann** [comment]
I did some additional and discovered some problems with token revocation with unity. I'll contact Sander and Krzysztof.
