### ISSUE TITLE
oidc-agent logo as SVG file

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#371]
Hi,

I would be great if the oidc-agent logo were available as an SVG file.

SVG is a vector format, which means the output will look the best on whichever media resolution it's being deployed.

Also, you might like to consider a version of the logo with a white background, as this often works better when viewed on certain media.

Cheers,
Paul.

**Comment by zachmann** [comment]
I added different versions of the logo to the logos dir:
https://github.com/indigo-dc/oidc-agent/tree/master/logos

There are six different versions:
- dark background and white writing (what we use as the default logo)
- dark background and transparent writing
- white background and dark writing
- white background and transparent writing
- transparent background and dark writing
- transparent background and white writing

All six versions are available as svg and png

**Comment by paulmillar** [comment]
Thanks!
