### ISSUE TITLE
list.o is not generated due to to missing  /sbin/ldconfig

### ISSUE THREAD

**Issue by FFFreisl** [indigo-dc/oidc-agent#389]
Im working on a Windows PC with Msys2.
make, compiled all the files.
At some point i had the following error:

/usr/lib/gcc/x86_64-pc-msys/11.2.0/../../../../x86_64-pc-msys/bin/ld: cannot find -llist
collect2: error: ld returned 1 exit status
Reaping losing child 0x8000ae190 PID 6802
make: *** [Makefile:334: bin/oidc-agent] Error 1

My quickfix was to change this line, se below
https://github.com/indigo-dc/oidc-agent/blob/7d4ad3c179c9492d4aa4b411368727059b5841ca/Makefile#L67

to 
USE_LIST_SO ?= $(shell echo 0)

after this i executed "make" again.  list.o now was created and the executables in the bin folder too.

/sbin/ldconfig --> not available on a Windows Pc
USE_LIST_SO was always 1 ....

**Comment by marcvs** [comment]
Many thanks; We're working on improving the windows builds and providing an installer. 
Your feedback will speed up my work (as I'm really not familiar with windows)

**Comment by FFFreisl** [comment]
@marcvs MSYS2.
But at the moment i cant reproduce the situation described above, i don't know why.
When i undo my change and do:
1 make clean
2 make
list.o is created and there is no linking error.
USE_LIST_SO for some reason is now always 0

According to pacmanlog last thing i did:
installed mingw-w64-x86_64-libconfig (1.7.2-2)
installed mingw-w64-x86_64-grep (3.6-1)

**Comment by marcvs** [comment]
This is fine. `USE_LIST_SO=0` basically means, that we compile the version that we ship (and do not `use` the installed version).
