### ISSUE TITLE
Support listing the loaded OPs without any embellishment

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#395]
I have a script that iterates over the loaded OPs to build suitable dCache configuration for testing.

This script uses the `oidc-add -a` output to learn which OPs are currently loaded.

Currently, the output from `oidc-add -a` includes a header as a first line.  Here is an example:
>The following account configurations are currently loaded: 
>HELMHOLTZ
>ESCAPE
>WLCG

As a work-around, the script skips the first line of stdout, taking all subsequent lines as the names of loaded OPs.

However, it might be helpful if it were possible for `oidc-add -a` to refrain from printing this header, so it would only list the loaded OPs.

**Comment by zachmann** [comment]
I don't think it is much of a problem to skip the first line with:
```
oidc-add -a | tail -n +2
```

I think adding an additional option or parameter bloats the tool much. However, what we can do is printing the first line to `stderr` and only the actual content to `stdout`. This way you can easily get the desired output in the script.

**Comment by paulmillar** [comment]
I'm a little torn on this one.

Certainly, skipping the first line isn't hard to do.

The header text (`The following ...`) is, IMHO, redundant.  The user specified the `-a` option, so they should know what the output means.  That said, people often like some redundancy to make things clear(er).

Another approach I've see is where a command changes the output depending on whether or not stdout is connected to a terminal.  IIRC, `git` does this by switching off the ANSI colour sequences if the output is piped to another command.

Using both stderr/stdout might work, but it strikes me as a somewhat awkward/messy solution.

**Comment by zachmann** [comment]
> The header text (`The following ...`) is, IMHO, redundant. The user specified the `-a` option, so they should know what the output means. That said, people often like some redundancy to make things clear(er).

You're right with both points. I would like to keep it, since in my opinion hte `-l` and `-a` options can easily be confused, and the header explains if these are the available or loaded accounts.

> Another approach I've see is where a command changes the output depending on whether or not stdout is connected to a terminal. IIRC, `git` does this by switching off the ANSI colour sequences if the output is piped to another command.

That's certainly an option, and it also isn't that hard to do.
Btw. we do the same and also switch off the ANSI color sequences if not connected to a tty.
