### ISSUE TITLE
rpm makefile target rpmsource: version release from debian

### ISSUE THREAD

**Issue by zachmann** [indigo-dc/oidc-agent#399]
The `rpmsource` makefile target extracts the version and release from the debian changelog. This is:
- strange, since version can be extracted from the `VERSION` file, and release is not necessarily the same for rpm and debian
- not possible anymore, since we dropped the debian folder

https://github.com/indigo-dc/oidc-agent/blob/acdfdaf96ae71908291b251f8bf26c4de22a48a4/Makefile#L723-L725

Please fix this. I guess it is not needed at all, and we simply can hardcode (and update) version and release in the rpm spec file. 
That's actually what we currently do, isn't it? 
I also cannot find the `DO_NOT_REPLACE_THIS_LINE` line in `rpm/oidc-agent.spec` so I guess, this is not used at all anymore and we can drop it, right?

**Comment by marcvs** [comment]
I had it in there because I didn't like changing the version in multiple places.

I used the debian/changelog because I didn't want to automatise that one.

Give me 30min to make a test-run on copr.

**Comment by marcvs** [comment]
Ok; works for all (ecept epel7, which is probably a different error)
