### ISSUE TITLE
Registering new client fails with "could not decode json: (null)"

### ISSUE THREAD

**Issue by marcvs** [indigo-dc/oidc-agent#40]
When registering a new client using oidc-gen new-iam I get this error:

marcus@nemo:~/grid/m-team/oidc-agent-deb/oidc-agent$ oidc-gen new-iam
Cert Path [/etc/ssl/certs/ca-certificates.crt]: 
[1] https://iam-test.indigo-datacloud.eu/
Issuer [https://iam-test.indigo-datacloud.eu/]: 
Could not decode json: (null)
This seems to be a bug. Please hand in a bug report.

I was also using the /oidc and /oauth2 paths.

The error already appears before IAM could have possibly answered the request.

**Comment by zachmann** [comment]
If I remember right, it is currently possible that this error message is returned when oidc-gen cannot conenct to oidc-agent. 
Is oidc-agent running and the environment variable correctly set?
If this is not the problem I have to look into it.

**Comment by marcvs** [comment]
Ok, in part it was my bad. Thanks for updating the error message
