### ISSUE TITLE
yum on centos 8 installing fails because of libsodium dependenct

### ISSUE THREAD

**Issue by ygrange** [indigo-dc/oidc-agent#407]
Heya,

I'm trying to install `oidc-agent-cli` in de Docker container running centos 8 (since I do not need desktop bindings and `oidc-agent` fails due to yad). 

So I basicallt followd the instructions to install the data.kit.edu repo on centos8 from their website. Then I type `yum install oidc-agent-cli` which fails with:

```
# yum install oidc-agent-cli
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:01:52 ago on Mon Apr  4 13:40:54 2022.
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides libsodium.so.23()(64bit) needed by oidc-agent-cli-4.2.6-1.el8.x86_64
  - nothing provides libsodium >= 1.0.18 needed by oidc-agent-cli-4.2.6-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

I haven't tried too much to debug but this may be a known issue (though I cannot find it in the closed issues list).

**Comment by ygrange** [comment]
Oh, for some reason I only realised `epel` existed after submitting this issue. Installing epel seems to have done the trick!

**Comment by marcvs** [comment]
Yes, I was just about to check, where the libsodium package comes from :)
