### ISSUE TITLE
Support for PKCE; in particular, with public clients

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#420]
Hi,

I was wondering whether oidc-agent supports the PKCE extension?

I believe this makes the most sense when working with public clients.  Using PKCE would help reduce the risk from an attacker obtaining the grant from the redirection and (knowing the public client's secret) is able to fetch the access token.

If oidc-agent already supports PKCE, great!

If not, are you considering adding support?

Cheers,
Paul.

**Comment by zachmann** [comment]
Yes oidc-agent supports PKCE.
