### ISSUE TITLE
oidc-gen error the other party disconnected

### ISSUE THREAD

**Issue by nulltrope** [indigo-dc/oidc-agent#424]
Hi, I recently upgraded to 4.2.6 after not using oidc-agent for some time and when trying to add a new account configuration e.g. with 
```
oidc-gen --debug --verbose --manual --client-id=<account name> --client-secret="" --scope=max --iss=<issuer url> --port=4242 --flow=code account-foo --debug --verbose
```

I get an error like:
```
Error while retrieving supported scopes for '<issuer url>': the other party disconnected
```

We have not made any changes to our identity provider/issuer, and it's unclear to me whether this error means there was an issue communicating with the local agent, or the agent had an error communicating with the issuer?

I don't see much useful detail in the logs either, aside from the final line which is:
```
2022-05-24 17:36:19 oidc-gen DEBUG: Parsing json '{"status":"failure","error":"the other party disconnected"}'
```

Additionally, it looks like `oidc-agent` is not versioned on Homebrew, so I don't think I can easily downgrade back to the last version I was on to verify it is not related to the upgrade.

If it helps, I'm running on MacOS Monterey 12.3.1

Let me know if you have any ideas on how to debug further, thanks!

**Comment by zachmann** [comment]
The error is a bit unusual. Since you mentioned that you didn;t use the agent for a while, my first idea would be that the agent version might not be compatible with the oidc-gen version.

Did you restart the agent, i.e. the agent runs version 4.2.6? You can check the version of the running agent with `oidc-agent --status`

**Comment by marcvs** [comment]
Not sure if this helps, but there was no new release since 4.2.6, which came out on Jan 13. I don't think it's any version related issue.

**Comment by zachmann** [comment]
While that's true, as I understood he only recently updated to 4.2.6

Also on MacOS 4.2.6 is the first and only version where we now (since April) offer bottles.

**Comment by nulltrope** [comment]
> The error is a bit unusual. Since you mentioned that you didn;t use the agent for a while, my first idea would be that the agent version might not be compatible with the oidc-gen version.
> 
> Did you restart the agent, i.e. the agent runs version 4.2.6? You can check the version of the running agent with `oidc-agent --status`

I verified both versions are the same:

```
oidc-agent --version
oidc-agent 4.2.6

oidc-gen --version
oidc-gen 4.2.6
```

> Not sure if this helps, but there was no new release since 4.2.6, which came out on Jan 13. I don't think it's any version related issue.

Sorry should have been more clear, I was running on version 4.2.1 previously and had not used oidc-agent since then. I just upgraded yesterday to the latest, which was 4.2.6

**Comment by nulltrope** [comment]
Aha! Looks like I did indeed have old oidc-agent process(es) running in the background. I managed to `kill` them and restart oidc-agent with the proper version (looks like it now launches from `/usr/local/Cellar/`)

Small nit but any chance we could improve the error messaging here to make it more clear that the error is communicating between the CLI and the agent, and not the agent and the issuer?

**Comment by zachmann** [comment]
Usually, if the error is while communicating with the OP, the error message will indicate this more clearly, e.g. with `OIDC error` or a message that the agent could not connect to the issuer (and will suggest that this is properly because of a network issue).

So I think the error message is fine, esp since it is hard to reproduce.
