### ISSUE TITLE
update README / install instructions

### ISSUE THREAD

**Issue by shallmann** [indigo-dc/oidc-agent#429]
Some install instructions are outdated and therefore confusing for less experienced users:
For Ubuntu, running:
`sudo add-apt-repository "deb http://repo.data.kit.edu/ubuntu/bionic ./"`
with a different ubuntu version than bionic will not work (and manual removal is required afterwards when adding the correct one)
For MacOS `brew cask install xxx` should be replaced by `brew install xxx --cask`

**Comment by zachmann** [comment]
Thanks for the heads-up. 
The installation instructions on http://repo.data.kit.edu should be fine for ubuntu. 

For Macos the cask install is no longer needed and I did update the instructions in the gitbook, but forgot to update it in the Readme.

I now updated the Readme with the up-to-date instructions.
