### ISSUE TITLE
Google device flow

### ISSUE THREAD

**Issue by ondrejvelisek** [indigo-dc/oidc-agent#43]
I'm not able to register Google device flow client. Neither manually nor from file. It says. Error: Device Flow not Supported. However Google supports it ([doc](https://developers.google.com/identity/protocols/OAuth2ForDevices)). Maybe it is because googles .well-known configuration endpoint does not provide "device_authorization_endpoint" key. Is tehre a way to enter it maually?

**Comment by zachmann** [comment]
You are right that this is because google does not provide the device authorization endpoint in the .wellknown configuration.
There currently is no way implemented to set the endpoint manually, but we can add it.
Alternatively you can use the authorization code flow.

**Comment by ondrejvelisek** [comment]
I'm forced to use device flow (Virtual machine with no GUI). For now I will use different IdP for development however If it is not a big deal I would appreciate implementation on your side. Thanks for the quict response!

**Comment by zachmann** [comment]
I implemented the possibility to specify the device authorization endpoint with the ```--dae``` option. 
You should now be able to use the following command.
```
oidc-gen google -m --flow=device --dae=https://accounts.google.com/o/oauth2/device/code
```
Note that for google the registered client has to be of type 'Other' and not 'Web application'.
Please test it and report back.

Note also that account configuration files can be copied to another machine. So one could generate the config on one machine (with a browser) and then copy it to another machine for usage.

**Comment by ondrejvelisek** [comment]
Yep. Works like a charm! Thank you!
