### ISSUE TITLE
liboidc-agent.so.4 not found

### ISSUE THREAD

**Issue by egazzarr** [indigo-dc/oidc-agent#445]
Hello again, on my CentOS Linux release 8.5.2111 machine when I run:

` oidc-token $TOKEN_NAME`

I get the following error: 

`oidc-token: error while loading shared libraries: liboidc-agent.so.4: cannot open shared object file: No such file or directory`

How do I solve this?

Thank you for your help!

**Comment by zachmann** [comment]
Did you install from package or how did you install oidc-agent?

**Comment by egazzarr** [comment]
From source, then tried to yum install from the cloned directory with `yum install oidc-agent ` and the error went away, but now the command just seems to be stuck and does not return anything..

**Comment by zachmann** [comment]
So `oidc-token` now finds the library but get stucks.
Do `oidc-gen` and `oidc-add` work normally or do they also have problems?

**Comment by egazzarr** [comment]
Hi, sorry forgot to reply, I made everything work finally, and found this alternative documentation which seems to have a much easier installation on centos systems: https://wlcg-authz-wg.github.io/wlcg-authz-docs/token-based-authorization/oidc-agent/. Thanks for your help anyways!
