### ISSUE TITLE
oidc-token stuck for a week, needs timeout

### ISSUE THREAD

**Issue by DrDaveD** [indigo-dc/oidc-agent#462]
We had a production case at Fermilab where an `oidc-token` process was stuck running for a week.  This was after an outage of the token issuer (CILogon) which is hosted in AWS.  I have seen similar issues before with other tools, and they were solved by adding network timeouts.  Can connect and read timeouts be added to `oidc-token` network calls?

This was from rpm `oidc-agent-4.2.4-1.1.osg35.el7.x86_64` built by OSG and it was invoked by the `osg-token-renewer` command.

@brianhlin @StevenCTimm

**Comment by zachmann** [comment]
Hi Dave,

[oidc-token does not do network calls, all entwork communication is done by the agent]

Network calls are done through libcurl; there is a default connect timeout of 300 seconds, but there was no read timeout set.

I added a (read) timeout of 180 seconds and reduced the connect timeout to 120.
In version 5 of oidc-agent we also can make these values easily configurable by the user.

**Comment by DrDaveD** [comment]
Ok, sounds good.

For version 5 also consider what would happen if the token issue is a round-robin DNS of more than one server (like CILogon is) and if one of the servers is not responding.  Would the request time out in a reasonable amount of time and move on to try the other server?  Or would ~half the requests fail?

**Comment by zachmann** [comment]
Currently, yes significant portion of requests would fail.
In 4.4.2 I added a retry mechanism and further reduced the timeout values.
