### ISSUE TITLE
4.4.2 RPMs: oidc-agent-desktop no longer available but still required

### ISSUE THREAD

**Issue by jouvin** [indigo-dc/oidc-agent#470]
Hi,

I have been trying to upgrade our 4.2.x oidc-agent to a recent version using the last version available in the YUM repo https://repo.data.kit.edu/centos/7 (same pb with centos/8), 4.4.2. Unfortunately, it seems the `oidc-agent` RPM is broken as it requires `oidc-agent-desktop` 4.4.2 which is no longer available (probably as a consequence of effort to put OIDC agent in EPEL without the graphics component as discussed in #267). I don't need the graphics component but I'd like to be able to install the last version! Is it a known issue?

Michel

**Comment by zachmann** [comment]
For the time-being just install `oidc-agent-cli`. `oidc-agent` is a metapackage that (normally) installs both.

**Comment by jouvin** [comment]
Thanks! I missed that.

**Comment by marcvs** [comment]
Actually this is partially a bug I introduced into the rpm spec file, when trying to conditionally build oidc-agent-desktop.
I'll file a PR to fix that against `prerel` in a bit.
@jouvin You should see an updated -4.4.2-2 version soon.
