### ISSUE TITLE
make fails on arch linux as ld cannot find -llist

### ISSUE THREAD

**Issue by arthuradriaens-code** [indigo-dc/oidc-agent#488]
ERROR: ld: cannot find -llist: No such file or directory

I installed all the required libraries to build from source but when
ld searches for liblist, it can't find it. What is this and where should I be able to find it?

Kind regards

**Comment by zachmann** [comment]
Please try to build with `make USE_LIST_SO=0`.

It is [this list library](https://github.com/clibs/list) which is currently packaged for debian.
There is a mechanism in place to discover if the lib is installed and if it is used, if not the source files are compiled and the library is not required.

The above command disables the usage of the lib and uses the source files instead.

**Comment by arthuradriaens-code** [comment]
This indeed works, thanks!
