### ISSUE TITLE
Support for issue #200 

### ISSUE THREAD

**Issue by SofianeB** [indigo-dc/oidc-agent#49]
Hi, 

I didn't know exactly if it was the right place. 
Can you help on this? 

https://github.com/indigo-dc/oidcc/issues/200

Thank you. 

Best, 

Sofiane.

**Comment by marcvs** [comment]
Hi,

what's up?

On 07/17/18 00:51, SB wrote:
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/indigo-dc/oidc-agent/issues/49

-- 
Marcus.

**Comment by SofianeB** [comment]
I am trying to connect our jupyterhub instance via keycloak to INDIGO IAM (https://iam-test.indigo-datacloud.eu/.well-known/openid-configuration). The redirection to the login/confirmation page works perfectly.
Unfortunately, I am getting cannot get access_token from server.

Did I miss something during configuration?

I created an account and then a client, exported the JSON file and upload it to keycloak.

**Comment by marcvs** [comment]
Well, it's not related to OIDCC.

However, if you're using the oidc-agent to obtain an AT (e.g. from IAM)
and want to use that to access jupyter notebooks (which I find an
interesting case) you're most welcome!

M.

On 07/17/18 08:28, SB wrote:
> I though that INDIGO DC IAM is related to OIDCC. Maybe I am wrong. You can close this if this is the case.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/indigo-dc/oidc-agent/issues/49#issuecomment-405502460

-- 
Marcus.

**Comment by SofianeB** [comment]
Thanks @marcvs I don't what just happened now, but the integration is working!
