### ISSUE TITLE
bug: oidc-agent-service wrongly configures the oidc-agent executable default path

### ISSUE THREAD

**Issue by carmelopellegrino** [indigo-dc/oidc-agent#490]
Hello,

since a couple of releases of the oidc-agent RPM package, at line 56 of the script the initialisation of the OIDC_AGENT environment variable has the wrong default value `/usr/bin/bin/oidc-agent`. This impedes the use of `oidc-agent-service use` command (which is also used by oidc-keychain) to launch oidc-agent, unless the env var `OIDC_AGENT` is set to the correct path (`/usr/bin/oidc-agent`) elsewhere.

Could you please fix it for RPM distribution?

DEB packages are not affected.

**Comment by marcvs** [comment]
Thanks for reporting. I'll be on it next week.

**Comment by marcvs** [comment]
The fixed version is now available for this subset of supported
distributions at https://repo.data.kit.edu/devel for this subset of
supported linux distributions:

- centos 7
- opensuse 15.5
- ubuntu kinetic kudu
- debian bookworm

Please let me know if you need additional distributions for early access.

Unfortunately, the merge to prerel may still need some time.

**Comment by marcvs** [comment]
All supported linux platforms are now available on prerel repository as 4.5.2~pr17-1
