### ISSUE TITLE
Update on IAM's "OAuth Error"

### ISSUE THREAD

**Issue by marcvs** [indigo-dc/oidc-agent#496]
When running oidc-gen with wlcg IAM and the authcode flow, I sometimes get an OAuth error, depending (drumrolls) on the `scope` list.

This works fine:
```
oidc-gen --pub --iss https://wlcg.cloud.cnaf.infn.it  --scope "eduperson_entitlement email wlcg wlcg.groups" wlcg-demo-works
```

This reproduces the error:
```
oidc-gen --pub --iss https://wlcg.cloud.cnaf.infn.it  --scope "eduperson_entitlement email wlcg wlcg.groups storage.read:/" wlcg-demo-fails
```

```
Error:
   OAuth Error

error="invalid_request", error_description="Changes were detected from the original authorization request."
```

**Comment by zachmann** [comment]
This is not related to `oidc-agent`, but to WLCG IAM:
> The problem is related to some scope policies which allow access to storage.* scopes only to users belonging to wlcg/xfer group and compute.* scopes only to users belonging to wlcg/pilot group.

If you want to use these scpes, make sure you are in those groups.
