### ISSUE TITLE
Consider restarting oic-agent after package upgrade

### ISSUE THREAD

**Issue by marcvs** [indigo-dc/oidc-agent#499]

**Comment by marcvs** [comment]
debian: PR made in `codebase`
rpm: won't fix, since rpm does not provide install scripts with version of previous package.

**Comment by zachmann** [comment]
This was added to oidc-agent 5.2.0

Agents that have this enabled (default for oidc-agent-service started agents) of at least version 5.2.0 will be restarted on future updates.
