### ISSUE TITLE
Unable to specify a path for rediection URL

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#50]
When running `oidc-gen -m` the user is prompted for a list of redirect URIs.

There are two problems:

1. It seems that the redirection URL is required not to have a path.  For example, `http://localhost:8888` is OK, but `http://localhost:8888/` is not OK.

2. The problem is not picked up straight away: if the format requires exactly http://localhost:<number> then the input should be validated and an error returned straight away.

**Comment by zachmann** [comment]
1. It is correct that redirect urls are expected to have no path. However, oidc-gen now accepts urls with a trailing slash.

2. input is now validated and an error is returned if the input does not correspond to the required format.

**Comment by paulmillar** [comment]
That sounds great -- feel free to close this issue once the code is updated with these changes.

**Comment by zachmann** [comment]
Correction: Also other redirect uris are accepted, e.g. ```http:localhost:8080/redirect```

**Comment by zachmann** [comment]
Changes included in v1.2.8
