### ISSUE TITLE
Windows 10 installation

### ISSUE THREAD

**Issue by jaceksocha** [indigo-dc/oidc-agent#521]
Hi, we are facing some problem during oidc agent installation on Windows 10 pro

![MicrosoftTeams-image (2)](https://github.com/indigo-dc/oidc-agent/assets/5284905/30027e7c-25e2-4cb8-8f7a-8c8251935c2c)
![MicrosoftTeams-image (1)](https://github.com/indigo-dc/oidc-agent/assets/5284905/551c43ba-1616-4c1f-b1c9-9483f4a1f67d)

![MicrosoftTeams-image (3)](https://github.com/indigo-dc/oidc-agent/assets/5284905/8d5c7969-4476-46fc-88aa-e99e86adff62)

Looks like missing libraries
`libbrotlienc.dll , libbrotlidec.dll, libprce2-8-0.dll`

Installers from http://repo.data.kit.edu/windows/oidc-agent/
Below behavior is on latest version.

Have you encountered this problem?

Greetings

**Comment by tabramczyk** [comment]
I installed this 3 libs and than I needed to install `libbrotlicommon.dll` too.

I got error that there is no method `BrotliDefaultAllocFunc` in `libbrotlienc.dll`. 
Unfortunately idk what version of libs we need.

**Comment by marcvs** [comment]
Hi There,
Thanks for this. These libs will be shipped in the next version of the windows lib. They used to be, so I'm a bit puzzled why they're not.
I'll take a look in the coming week.

**Comment by marcvs** [comment]
Hi There,

could you please try installing this one (uninstall the current installation first, please)
https://repo.data.kit.edu/devel/windows/oidc-agent/

**Comment by tabramczyk** [comment]
I've installed version 5.0.1 and I see error:
```
> oidc-gen.exe loki-auth --issuer=https://login.microsoftonline.com/****/v2.0 --flow=device --pub --client-id=**** --client-secret="" --redirect-url=http://localhost:1234/ --scope=profile                                                                           
No account exists with this short name. Creating new configuration ...                                                  
Exception: STATUS_ACCESS_VIOLATION at rip=000100415519
```

**Comment by marcvs** [comment]
Ok; so there is our transition from version 4 for version 5, which is scheduled to happen this summer. I'm in charge of windows, and will fix it in the coming days.

**Comment by jaceksocha** [comment]
Thank you @marcvs , please let us know if update arrived.

Greetings

**Comment by marcvs** [comment]
Hi @jaceksocha , I finally got at looking at this. 
Trouble is, that I can't reproduce it.
Could you try this cmdline:
`oidc-gen.exe loki-auth --issuer=https://aai.egi.eu/auth/realms/egi --flow=device --pub --client-id=oidc-agent --client-secret="" --redirect-url=http://localhost:1234/ --scope=profile`

**Comment by tabramczyk** [comment]
pr120 works correctly. Thank you for help. 

We're waiting for release. :)

Greetings

**Comment by jaceksocha** [comment]
@marcvs thank you for bugfix.
Is it possible to provide time-estimate when you plan deploy version 5 (containing bugfix for windows)?

Greetings

**Comment by zachmann** [comment]
We're still working on some smaller bugfixes. The plan is to release oidc-agent 5 in the near future, but there is no exact time estimate.

**Comment by marcvs** [comment]
Regarding windows, I don't want to have it done by end of thursday

**Comment by zachmann** [comment]
> @marcvs thank you for bugfix. Is it possible to provide time-estimate when you plan deploy version 5 (containing bugfix for windows)?
> 
> Greetings

We just officially released oidc-agent 5. The installer is available at: http://repo.data.kit.edu/windows/oidc-agent/
