### ISSUE TITLE
access-token is not cache

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#53]
Each time I run the `oidc-token` command it generates a fresh access token.

Some services and OPs allow an access token to be reused within some validity period.  For such services, caching the access token can lead to significant improvement in responsiveness.

This could be done within oidc-agent (to allow caching across multiple clients) or implemented specifically for oidc-token.

**Comment by zachmann** [comment]
oidc-agent does cache the access token. Running oidc-token twice should return the same access token. The ```-t``` option can be used to specify the time in seconds the access token should be valid. If no value is provided, 0 is used.
oidc-agent checks if the currently cached access token is valid for the specified time. If not and only if not a new access token is requested at the OP. 

However, if the ```--scope``` option is used, no caching is used and a new access token is created for every request.
Did you use this option, or do you also get fresh access tokens when calling oidc-token without any options?

**Comment by paulmillar** [comment]
Thanks for the quick response.

I've investigate some more.  It seems the OP response does *not* include the `expires_in` claim.

AFAIK, this makes it impossible for oidc-agent to cache the response, and oidc-agent is behaving correctly.

I can try to work around this by caching the token locally and refreshing when the protected resource returns an authentication error.  More work for me, but should be doable.

In the mean time, I think this issue should be closed.
