### ISSUE TITLE
Spec File No Longer Available

### ISSUE THREAD

**Issue by mwestphall** [indigo-dc/oidc-agent#534]
Hi all,

We're trying to build a new release of oidc-agent for the next OSG release series. It looks like the spec file is no longer available as of this merge: https://github.com/indigo-dc/oidc-agent/commit/bac858b5764f872b648ced011ea7c3c72d5780a2 . Is the removal of the spec file intended? If so, would you be able to provide us with guidance for how to obtain SRPMs for more recent releases of oidc-agent?

Thanks,
Matt

**Comment by marcvs** [comment]
We moved all packaging files from the main branches to the packaging/*
branches[1], which we don't maintain on github.

Please also note that we've recently been successful in getting our
package into fedora[2]. Of course, building from `prerel` will give you 
the latest (almost-totally-stable(TM)) version.

[1] https://git.scc.kit.edu/m-team/oidc-agent/-/tree/packaging/latest
[2] https://packages.fedoraproject.org/pkgs/oidc-agent/

M.

**Comment by marcvs** [comment]
Plans: yes. I underestimated the effort of getting packages in linux distributions (and keeping them up-to-date), though.
Also: I'm not super familiar with the RPM-based distro universe. I was hoping that EPEL and fedora are quite closely related.

If there is any experience in getting packages to EPEL, help would be greatly appreciated.

**Comment by zachmann** [comment]
Actually EPEL and fedora are closely related. According to https://repology.org/project/oidc-agent/packages
at least 4.5.2 is available in EPEL.

For `oidc-agent-cli` see also: https://packages.fedoraproject.org/pkgs/oidc-agent/oidc-agent-cli/

**Comment by mwestphall** [comment]
We were able to rebuild oidc-agent for OSG with the EPEL srpm and spec file from the packaging repo. Thanks!
