### ISSUE TITLE
oidc-agent no-prompt

### ISSUE THREAD

**Issue by jaceksocha** [indigo-dc/oidc-agent#548]
Hi

I've question, is it possible to use oidc-agent without "prompt windows" ? , if yes then how configure ?
I mean whole communication between agent and user via console.

Greetings

**Comment by zachmann** [comment]
The command line tools like `oidc-gen`, `oidc-add`, `oidc-token` will prompt on console by default.
The daemon `oidc-agent` occassionally also has the need to prompt the user and does this via `oidc-prompt` on the GUI. `oidc-agent` has no terminal attached so there is no other way.

However, if only the `oidc-agent-cli` package is installed (not `oidc-agent-desktop` which is installed by `oidc-agent` package) then `oidc-prompt` is not installed and no prompting will / can happen.

However, this might reduce user experience in some use cases, i.e. no autoload is possbile. But of course there are uses cases where this makes sense.

Especially regarding autoload the number of prompts can be greatly reduced by using one of these approaches:
- gpg-based encryption of the configuration
- configure oidc-agent to keep the password in memory
- manually tell oidc-agent to do so by loading with `oidc-add --pw-store`
