### ISSUE TITLE
Issuer redirects respond with something fishy

### ISSUE THREAD

**Issue by nicholas-wilson-au** [indigo-dc/oidc-agent#606]
When using an issuer that may redirect elsewhere, I am seeing the error:
`Error while retrieving supported scopes for '$OIDC_URL': Provider uses another issuer url than expected. Something is fishy.`
in version 5.2.2 (Fedora) and 4.6.0 (OpenSUSE) @dragotin however, this issue is not present in version 4.2.6 (Ubuntu).

This looks to be caused by this commit:
https://github.com/indigo-dc/oidc-agent/commit/a346fb32a49f390e3dedf75f873239090d9feec8

I am testing this with ownCloud Infinite Scale test instance with keycloak https://owncloud.dev/ocis/deployment/continuous_deployment/#ocis-with-keycloak

When setting the issuer as follows results in this error
`$OIDC_URL = https://ocis.ocis-keycloak.rolling.owncloud.works`
(https://ocis.ocis-keycloak.rolling.owncloud.works/.well-known/openid-configuration)
even when directly calling the realm it also fails
`$OIDC_URL = https://keycloak.ocis-keycloak.rolling.owncloud.works/realms/oCIS`
(https://keycloak.ocis-keycloak.rolling.owncloud.works/realms/oCIS/.well-known/openid-configuration)

```
oidc-gen \
 --flow=code \
 --no-webserver \
 --client-id=xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69 \
 --client-secret=UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh \
 --issuer $OIDC_URL \
 --redirect-uri=http://localhost:8080 \
 --scope="openid offline_access profile email" \
 my-client
```

Both of these issuers work when using 4.2.6 on Ubunutu or Debian.

**Comment by zachmann** [comment]
You have to use the issuer url as it is advertised in the well-known openid configuration. The mentioned commit actually enforces this by checking that the advertised issuer is the same as the one provided by the user.

Your first url is not the same as the advertised issuer url, therefore it fails.
 with the mentioned error.

The second url, is correct and should work. 
I also verified that it does work (oidc-agent 5.2.2 on ubuntu)

Could you please verify again, that the second url is not working on fedora and can you alos try on ubuntu/debian?

**Comment by dragotin** [comment]
Thanks for your answer. 
The second URL is working also with newer versions of oidc-agent. 

However, the older versions also work with the ones that were announced through well-known. Any particular reason why that is not longer allowed? It makes working with oidc-agent more cumbersome IMHO.

**Comment by zachmann** [comment]
Well `oidc-agent` works with the correct issuer url. Generally, we use the information from the openid configuration endpoint. We find this by appending `/.well-known/openid-configuration` to the url passed by the user.
In older versions it was possible that multiple urls could point to the same document, with newer versions we check that the issuer url provided by the user matches the issuer url provided by the issuer. 
This is done to ensure that we don't talk to an unexpected entity.
