### ISSUE TITLE
Removing support for obtaining the list of currently loaded configurations

### ISSUE THREAD

**Issue by zachmann** [indigo-dc/oidc-agent#70]
The C- and IPC-API can currently obtain a list of the loaded account configurations. This makes it easier for an application to obtain an access token that is not meant for it.
Also an application requesting an access token for a certain configuration does not have to check if this configuration is really loaded. It simply can try to obtain an access token. If it isn't loaded oidc-agent will return an error message. 
Also #67 suggest that in this case the case can be asked if it wants to load the configuration ("on the fly").

**Comment by zachmann** [comment]
However, a user still might want to use the ```oidc-token -l``` option to check which configuration are currently loaded. We would have to drop that feature, if we include this change.

**Comment by marcvs** [comment]
As we discussed, we can drop this feature.

**Comment by zachmann** [comment]
Included in dev in commit 58361fc
