### ISSUE TITLE
Support for Token Exchange

### ISSUE THREAD

**Issue by zachmann** [indigo-dc/oidc-agent#93]
Add support for token exchange: https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-16

**Comment by paulmillar** [comment]
Is the idea here that supporting OAuth token exchange would allow oidc-agent to present a valid access token to the OP and obtain (from the OP) a refresh token?

**Comment by zachmann** [comment]
Yes, this could be used as a another way to obtain the RT. So instead of doing the auth code flow or device flow a user just provides an AT. However, usually the token exchange grant is not enabled for any clients, for good reasons. So this only works with clients that have the token exchange grant, i.e. the user has to provide the client credentials for such a client, since oidc-agent cannot get this dynamically.

**Comment by paulmillar** [comment]
The particular use-case I had in mind involves deploying oidc-agent "in the cloud'.

The scenario has the user authenticate with a PaaS system via OIDC, with the framework passing the AT to the virtual machine.  A service, running on that machine, needs to authenticate with another service using OIDC, potentially over a longer period than the AT is valid.  This should be done autonomously, without the virtual machine "tethered" to some existing oidc-agent (e.g., the user's desktop machine).

I could imagine there would need to be some way the user can "bless" the virtual machine, so the OP authorises the token exchange.  As you say, the token exchange grant is not providing by default, for good reasons.

**Comment by zachmann** [comment]
@marcvs this sounds like another case of the mytoken / long running jobs use case.
@paulmillar Depending on the exact requirements this might be possible with a preregistered client that has the token exchange grant type. However, if I understand the use case correctly this sounds like a familiar problem that many communities have right now. We have the idea of a mytoken service that can be seen as centralized version of oidc-agent. I or @marcvs can provide more details on it, when needed. In this case I suggest to move the discussion to another place.

**Comment by zachmann** [comment]
Closing this for now. I feel like oidc-agent does not need support for token exchange and mytoken is probably a better tool for possible use cases.

**Comment by paulmillar** [comment]
Hi @zachmann,

Just to add my 2c worth, here.

I'm not 100% convinced that mytoken is necessarily a better option than using token-exchange: the OAuth2 token exchange protocol has the advantage of being an open standard that many OPs already support.

That said, using oidc-agent to support long-running jobs does seem a bit of a hack.

Perhaps another way to look at this is that long-running computational activity are supported within some framework (a batch system, cloud environment, Jupyter hub, etc.).  It's the responsibility of that framework to ensure the job has what it needs.  That might be done using mytoken, but it could also use some other mechanism (e.g., some Hashicorp Vault deployment, a cron job writing into a known location, ...)

In any case, I agree that supporting remote, long-running jobs isn't something that naturally matches (what I see as) oidc-agent's core use-cases.

**Comment by zachmann** [comment]
Hi @paulmillar,
yes I agree and I didn't mean to say that token exchange shouldn't be used or that mytoken is better than token exchange; just that mytoken supports such use cases better than oidc-agent.
